apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-pod2
spec:
  containers:
  - image: registry.docker.hub.com/nginx
    name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
