apiVersion: v1
kind: Pod
metadata:
  name: disallowed-example2
spec:
  containers:
  - env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysecret
    image: redis
    name: test
